// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB807WPNjSpKEn-hTQ49xdvAiGydKAoMAA',
    appId: '1:542116313899:web:caf6f78e55a9b1f27f636e',
    messagingSenderId: '542116313899',
    projectId: 'testsigninwith-3d237',
    authDomain: 'testsigninwith-3d237.firebaseapp.com',
    storageBucket: 'testsigninwith-3d237.appspot.com',
    measurementId: 'G-YNS8HVV4RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr7RS3Egw2tSptPbmY-ubKAyhPCcRiX4Q',
    appId: '1:542116313899:android:abdccae3f36b431a7f636e',
    messagingSenderId: '542116313899',
    projectId: 'testsigninwith-3d237',
    storageBucket: 'testsigninwith-3d237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYAyLNAjx13r7IwUThH_sx1VfgU4K8QYs',
    appId: '1:542116313899:ios:0fa439958041c6cc7f636e',
    messagingSenderId: '542116313899',
    projectId: 'testsigninwith-3d237',
    storageBucket: 'testsigninwith-3d237.appspot.com',
    androidClientId: '542116313899-trs5b4t4s8g66j0qdd8s18q44hhqb37l.apps.googleusercontent.com',
    iosClientId: '542116313899-av4qm9q158gbhorgnge800rvrdhg4pfe.apps.googleusercontent.com',
    iosBundleId: 'ir.devdecode.testflutterpackages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYAyLNAjx13r7IwUThH_sx1VfgU4K8QYs',
    appId: '1:542116313899:ios:0fa439958041c6cc7f636e',
    messagingSenderId: '542116313899',
    projectId: 'testsigninwith-3d237',
    storageBucket: 'testsigninwith-3d237.appspot.com',
    androidClientId: '542116313899-trs5b4t4s8g66j0qdd8s18q44hhqb37l.apps.googleusercontent.com',
    iosClientId: '542116313899-av4qm9q158gbhorgnge800rvrdhg4pfe.apps.googleusercontent.com',
    iosBundleId: 'ir.devdecode.testflutterpackages',
  );
}
